services:
  #---- Database (PostgreSQL) ----
  postgres:
    image: "postgres:16-alpine"
    container_name: "n8n-postgres"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    restart: unless-stopped
    networks:
      - n8n-network
  n8n:
    image: "n8nio/n8n:latest"
    container_name: "n8n-dev"
    expose:
      - "${N8N_PORT}"
      - "${N8N_RUNNERS_BROKER_PORT}"
    depends_on:
      - n8n-postgres
    environment:
      # ---- Bindings ----
      N8N_HOST: ${N8N_HOST}
      N8N_LISTEN_ADDRESS: ${N8N_LISTEN_ADDRESS}
      N8N_PORT: ${N8N_PORT}
      N8N_PROTOCOL: ${N8N_PROTOCOL}
      N8N_DISABLE_UI: "false"
    
      # ---- External Task Runners ----
      N8N_RUNNERS_ENABLED: ${N8N_RUNNERS_ENABLED}
      N8N_RUNNERS_MODE: ${N8N_RUNNERS_MODE}
      N8N_RUNNERS_BROKER_LISTEN_ADDRESS: ${N8N_RUNNERS_BROKER_LISTEN_ADDRESS}
      N8N_RUNNERS_AUTH_TOKEN: ${N8N_RUNNERS_AUTH_TOKEN}
      N8N_NATIVE_PYTHON_RUNNER: ${N8N_NATIVE_PYTHON_RUNNER}

      # ---- Timezone ----
      N8N_GENERIC_TIMEZONE: "Europe/Helsinki"
      TZ: "Europe/Helsinki"

      # ---- Database (PostgreSQL) ----
      DB_POSTGRESDB_HOST: ${POSTGRES_HOST}
      DB_POSTGRESDB_PORT: ${POSTGRES_PORT}
      DB_POSTGRESDB_DATABASE: "${POSTGRES_DATABASE}"
      DB_POSTGRESDB_USER: "${POSTGRES_USER}"
      DB_POSTGRESDB_PASSWORD: "${POSTGRES_PASSWORD}"

           # ---- Reverse proxy (NPM) ----
      # Public-facing HTTPS URL of your instance (via NPM)
      N8N_PUBLIC_URL: ${N8N_PUBLIC_URL}

      # Only needed if you plan to receive external webhooks:
      WEBHOOK_URL: ${WEBHOOK_URL}
  
      # ----task runners ----
  task-runners:
    image: n8nio/runners:latest
    container_name: n8n-runners-dev
    environment:
      N8N_RUNNERS_TASK_BROKER_URI: ${N8N_RUNNERS_TASK_BROKER_URI}
      N8N_RUNNERS_AUTH_TOKEN: ${N8N_RUNNERS_AUTH_TOKEN}
      N8N_RUNNERS_STDLIB_ALLOW: true
      N8N_GENERIC_TIMEZONE: Europe/Helsinki
      TZ: Europe/Helsinki
      
    depends_on:
      - n8n

    volumes:
      - "n8n_data:/home/node/.n8n"
    restart: unless-stopped
    networks:
      - n8n-network

networks:
  n8n-network:
    external: true

volumes:
  n8n_data:
  postgres_data: